-- Trust & Safety operations analytics query pack.
-- These queries are designed for the local SQLite review queue generated by
-- bluesky_integration/review_store.py. They are intentionally PM/Ops readable.

-- Queue health by status.
SELECT
  status,
  COUNT(*) AS item_count,
  ROUND(AVG(probability), 3) AS avg_model_probability,
  SUM(duplicate_count) AS total_observations
FROM review_items
GROUP BY status
ORDER BY item_count DESC, status;

-- Reviewer decision distribution.
SELECT
  COALESCE(reviewer_decision, 'unreviewed') AS reviewer_decision,
  COUNT(*) AS item_count
FROM review_items
GROUP BY COALESCE(reviewer_decision, 'unreviewed')
ORDER BY item_count DESC;

-- Action-tier distribution.
SELECT
  action,
  COUNT(*) AS item_count,
  ROUND(AVG(probability), 3) AS avg_model_probability
FROM review_items
GROUP BY action
ORDER BY item_count DESC;

-- Potential false-positive themes: items dismissed as not fraud.
SELECT
  uri,
  author_handle,
  ROUND(probability, 3) AS probability,
  action,
  reviewer_notes
FROM review_items
WHERE status = 'dismissed' OR reviewer_decision = 'not_fraud'
ORDER BY probability DESC;

-- Review coverage and backlog.
SELECT
  COUNT(*) AS total_items,
  SUM(CASE WHEN reviewer_decision IS NOT NULL THEN 1 ELSE 0 END) AS reviewed_items,
  SUM(CASE WHEN reviewer_decision IS NULL THEN 1 ELSE 0 END) AS unreviewed_items,
  ROUND(1.0 * SUM(CASE WHEN reviewer_decision IS NOT NULL THEN 1 ELSE 0 END) / COUNT(*), 3) AS review_coverage
FROM review_items;

-- Escalation candidates still waiting for action.
SELECT
  uri,
  author_handle,
  ROUND(probability, 3) AS probability,
  action,
  status,
  duplicate_count,
  substr(text, 1, 180) AS text_preview
FROM review_items
WHERE reviewer_decision IS NULL
ORDER BY
  CASE action
    WHEN 'high_confidence_escalation' THEN 1
    WHEN 'apply_potential_crypto_fraud_label' THEN 2
    WHEN 'send_to_human_review' THEN 3
    ELSE 4
  END,
  probability DESC;

-- Entity risk leaderboard for campaign intelligence.
SELECT
  e.entity_type,
  e.value,
  e.observation_count,
  ROUND(e.max_risk_weight, 3) AS max_risk_weight,
  COUNT(ie.uri) AS linked_items
FROM review_entities e
JOIN review_item_entities ie ON e.entity_id = ie.entity_id
GROUP BY e.entity_id, e.entity_type, e.value, e.observation_count, e.max_risk_weight
ORDER BY linked_items DESC, e.max_risk_weight DESC, e.value
LIMIT 20;

-- Reviewer event history for auditability.
SELECT
  event_type,
  COUNT(*) AS event_count,
  MIN(created_at) AS first_seen,
  MAX(created_at) AS last_seen
FROM review_events
GROUP BY event_type
ORDER BY event_count DESC;
