"""Scale simulation: what the thresholds cost at production volume.

Everything else in this repo works on hundreds of posts. Real Trust & Safety
work is dominated by what happens at six or seven orders of magnitude more —
where every threshold choice is a staffing decision, and "just route it to
review" has a payroll number attached.

This simulation models a 50,000-post synthetic day with a realistic scam
prevalence (~1.5%), scores a 6,000-post sample through the SAME
model and decision layer as the rest of the lab (scaled linearly to the daily
volume for reporting — sampling is itself a scale technique), and derives:

- measured action distribution vs. known ground truth (true prevalence is
  knowable here precisely because the corpus is synthetic — in production
  this requires labeled random sampling, never detection-derived counts);
- the review-queue load curve across candidate thresholds, translated into
  reviewers required and fully loaded cost per day;
- the precision/recall of the review net at each threshold — the tradeoff
  curve behind Decision Log entry 002;
- a 12-week transparency-style time series with two injected campaign waves,
  showing why point-in-time metrics mislead and trend reporting matters.

Deterministic (seeded); regenerated by the release pipeline.

Capacity assumptions (stated, not hidden): 90 s average handle time, 6
productive review hours/day, $38/hr fully loaded reviewer cost, single-review
workflow (no double-blind), no attrition buffer. Every one of these numbers
is disputable — that is why they are parameters.
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from datetime import datetime, timezone
from pathlib import Path

import joblib
import numpy as np

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

import policy_proposal_labeler_v2 as v2  # noqa: E402

HANDLE_TIME_S = 90
PRODUCTIVE_HOURS = 6
LOADED_RATE_HOURLY = 38.0
DECISIONS_PER_REVIEWER_DAY = int(PRODUCTIVE_HOURS * 3600 / HANDLE_TIME_S)

COINS = ["BTC", "ETH", "USDT", "SOL", "BNB", "ADA"]
CELEBS = ["Elon Musk", "CZ", "Vitalik", "Michael Saylor", "Cristiano Ronaldo"]
BRANDS = ["Binance", "Coinbase", "Kraken", "MetaMask", "Ledger"]
DOMAINS = [
    "claim-{coin}-now.xyz", "secure-{coin}-airdrop.top", "{brand}-rewards.cash",
    "official-{coin}-event.site", "get{coin}bonus.win",
]

FRAUD_TEMPLATES = [
    ("giveaway_double", "{celeb} {coin} giveaway is LIVE! Send {amt} {coin} to the verified wallet and receive {amt2} {coin} back instantly. Limited slots!"),
    ("drainer_airdrop", "FREE {coin} airdrop ending tonight! Connect your wallet at {domain} to claim your free {coin} before eligibility expires."),
    ("hyip", "Our AI trading bot delivers guaranteed {pct}% weekly returns, totally risk-free. Deposit {coin} today and watch it grow. DM to start."),
    ("recovery", "Lost crypto to a scam? Our certified recovery experts restore any wallet. Small processing fee upfront in {coin}, funds released same day."),
    ("support_phish", "{brand} support notice: unusual activity detected. Verify your wallet and send a small {coin} deposit to lift the account restriction."),
    ("promo_fee", "Congratulations! Your promo code unlocked {amt2} {coin}. Send the activation fee to the wallet address below and claim your prize now."),
    ("pump_group", "VIP signals group: {pct}% gains guaranteed on the next pump. Entry fee {amt} {coin}. Only serious traders, DM before we close."),
    ("mentor_funnel", "I turned $500 into $18k with my private method. I help beginners earn daily {coin} profits — DM me and I will show you where to deposit."),
]

LEGIT_TEMPLATES = [
    ("market", "{coin} moved {pct2}% today after the macro print. Volume looks thin though, curious what the weekend does."),
    ("market2", "Interesting quarter for {brand} — revenue up but trading volumes still below 2024 peaks. Long-term exchange thesis unclear."),
    ("news", "Regulators fined another fake {coin} investment platform today. Good reminder that guaranteed-return promises are the #1 red flag."),
    ("warning", "PSA: do NOT connect your wallet to random airdrop links. Drainers are everywhere this week. Stay safe out there."),
    ("question", "Is staking on {brand} worth it for small amounts of {coin}? Fees seem to eat most of the yield at my size."),
    ("question2", "Anyone compared hardware wallets lately? Torn between two options for storing {coin} long term."),
    ("dev", "Debugging a wallet-connect session bug in our testnet dapp — token refresh works, but the {coin} balance call intermittently 403s."),
    ("satire", "Send me one imaginary {coin} and I'll send back two imaginary {coin}, guaranteed by the Bank of Make-Believe."),
    ("help", "I think my uncle is caught in one of those {coin} doubling scams... he won't listen. How do I even report this?"),
    ("chatter", "Coffee, charts, and {coin} sideways action again. Riveting Tuesday."),
    ("chatter2", "Finally moved my {coin} off the exchange to cold storage. Should have done it months ago."),
    ("chatter3", "The {brand} app redesign is actually decent. Portfolio page loads way faster now."),
    ("chatter4", "Watching gas fees tonight like it's a sports match. Wild evening on chain."),
    ("nft", "Minted a little generative art piece today. Not selling anything, just enjoying the process."),
    ("macro", "CPI print tomorrow. Half my timeline says up, half says down. So, business as usual."),
    ("education", "Thread: how approval phishing works, why 'connect wallet' prompts on unknown sites are dangerous, and how to revoke allowances."),
    ("skeptic", "A platform is promising {pct}% monthly returns on {coin} deposits. Claims to be licensed offshore. I can't verify anything about them."),
]

# Weights: skeptical/edge legit content is rarer than chatter but present —
# it is the documented FP class, so it must exist in the corpus.
LEGIT_WEIGHTS = [16, 8, 4, 3, 10, 8, 3, 1, 2, 18, 12, 8, 6, 4, 3, 5, 2]


def fill(template: str, rng: random.Random) -> str:
    coin = rng.choice(COINS)
    amt = rng.choice(["0.05", "0.1", "0.2", "50", "100"])
    return (
        template.replace("{coin}", coin)
        .replace("{celeb}", rng.choice(CELEBS))
        .replace("{brand}", rng.choice(BRANDS))
        .replace("{domain}", rng.choice(DOMAINS).replace("{coin}", coin.lower()).replace("{brand}", rng.choice(BRANDS).lower()))
        .replace("{amt2}", rng.choice(["1", "2", "5", "200", "1000"]))
        .replace("{amt}", amt)
        .replace("{pct2}", rng.choice(["1.8", "3.2", "4.5", "0.6"]))
        .replace("{pct}", rng.choice(["10", "30", "100", "300"]))
    )


def generate_corpus(n_posts: int, prevalence: float, rng: random.Random):
    posts, labels, families = [], [], []
    for _ in range(n_posts):
        if rng.random() < prevalence:
            family, template = rng.choice(FRAUD_TEMPLATES)
            labels.append(1)
        else:
            family, template = rng.choices(LEGIT_TEMPLATES, weights=LEGIT_WEIGHTS, k=1)[0]
            labels.append(0)
        posts.append(fill(template, rng))
        families.append(family)
    return posts, labels, families


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--posts", type=int, default=6000, help="Sampled posts to score (scaled up to --daily-volume for reporting)")
    parser.add_argument("--daily-volume", type=int, default=50000)
    parser.add_argument("--prevalence", type=float, default=0.015)
    parser.add_argument("--seed", type=int, default=5342)
    parser.add_argument("--model-path", default="audit_outputs/fraud_labeler_v2.joblib")
    parser.add_argument("--out", required=True)
    parser.add_argument("--markdown-out")
    parser.add_argument("--lab-summary")
    args = parser.parse_args()

    rng = random.Random(args.seed)
    posts, labels, families = generate_corpus(args.posts, args.prevalence, rng)
    labels_arr = np.asarray(labels)

    artifact = joblib.load(args.model_path)
    pipeline, thresholds = artifact["model"], artifact["thresholds"]
    probabilities = pipeline.predict_proba(posts)[:, 1]

    scale = args.daily_volume / args.posts
    actions = [
        v2.decision_for_text(text, float(p), thresholds)
        for text, p in zip(posts, probabilities)
    ]
    action_counts: dict[str, int] = {}
    for action in actions:
        action_counts[action] = action_counts.get(action, 0) + 1

    true_prevalence = float(labels_arr.mean())
    label_actions = {"apply_potential_crypto_fraud_label", "high_confidence_escalation"}
    legit_labeled = sum(
        1 for a, y in zip(actions, labels) if y == 0 and a in label_actions
    )
    legit_total = int((labels_arr == 0).sum())
    false_label_share = legit_labeled / max(1, legit_total)
    review_mask = np.asarray([a != "no_label" for a in actions])
    flagged_prevalence = float(review_mask.mean())

    # Threshold sweep: queue load, staffing, cost, and review-net quality.
    sweep = []
    for threshold in [0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.55, 0.60]:
        queued = probabilities >= threshold
        queue_size = int(queued.sum())
        caught = int((queued & (labels_arr == 1)).sum())
        fraud_total = int(labels_arr.sum())
        reviewers = int(np.ceil(queue_size * scale / DECISIONS_PER_REVIEWER_DAY))
        daily_cost = reviewers * PRODUCTIVE_HOURS * LOADED_RATE_HOURLY
        sweep.append(
            {
                "threshold": threshold,
                "queuePerDay": int(queue_size * scale),
                "queueShare": round(queue_size / args.posts, 4),
                "reviewNetRecall": round(caught / max(1, fraud_total), 4),
                "reviewNetPrecision": round(caught / max(1, queue_size), 4),
                "reviewersNeeded": reviewers,
                "dailyReviewCost": round(daily_cost, 2),
                "costPerCaughtScam": round(daily_cost / max(1, caught * scale), 2),
            }
        )

    # 12-week transparency-style series with two campaign waves.
    weeks = []
    for week in range(1, 13):
        wave = 3.0 if week in (5, 9) else 1.0
        week_rng = random.Random(args.seed * 100 + week)
        week_prev = min(0.08, args.prevalence * wave * week_rng.uniform(0.85, 1.15))
        n_week = 7 * args.daily_volume
        fraud_n = int(n_week * week_prev)
        review_n = int(fraud_n * 0.986 + n_week * 0.0075)  # review recall + legit skeptic load
        label_n = int(fraud_n * 0.90)
        appeals = max(1, int(label_n * 0.012))
        weeks.append(
            {
                "week": week,
                "posts": n_week,
                "truePrevalencePct": round(week_prev * 100, 2),
                "reviewQueue": review_n,
                "labelsApplied": label_n,
                "appeals": appeals,
                "reversals": max(0, int(appeals * (0.25 if wave > 1 else 0.15))),
                "campaignWave": wave > 1,
            }
        )

    report = {
        "generatedAt": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "corpus": {
            "posts": args.posts,
            "dailyVolume": args.daily_volume,
            "seed": args.seed,
            "truePrevalence": round(true_prevalence, 4),
            "note": (
                "True prevalence is knowable here because the corpus is synthetic. "
                "In production this number requires labeled random sampling — "
                "detection-derived 'prevalence' measures what you catch, not what "
                "exists (see METRICS_DEFINITIONS.md)."
            ),
        },
        "assumptions": {
            "handleTimeSeconds": HANDLE_TIME_S,
            "productiveHoursPerDay": PRODUCTIVE_HOURS,
            "loadedHourlyRate": LOADED_RATE_HOURLY,
            "decisionsPerReviewerDay": DECISIONS_PER_REVIEWER_DAY,
        },
        "operatingPoint": {
            "actionCounts": action_counts,
            "flaggedShare": round(flagged_prevalence, 4),
            "falseLabelShareOnLegit": round(false_label_share, 4),
            "falseLabelNote": (
                "Share of legitimate posts reaching label-candidate or escalation "
                "before reviewer confirmation. Driven overwhelmingly by warning, "
                "news, and skeptical-reportage content — the same class the error "
                "analysis documents. At this volume it is the single strongest "
                "argument for stance-aware assistance on the review slice."
            ),
            "reviewersNeededAtOperatingPoint": int(
                np.ceil(
                    sum(1 for a in actions if a == "send_to_human_review")
                    * scale / DECISIONS_PER_REVIEWER_DAY
                )
            ),
        },
        "thresholdSweep": sweep,
        "weeklySeries": weeks,
        "interpretation": (
            "The sweep makes Decision Log 002 concrete: dropping the review "
            "threshold from 0.40 to 0.30 buys ~1 point of review-net recall and "
            "roughly doubles reviewer payroll. The campaign weeks in the series "
            "show the real staffing problem is burst capacity, not steady state — "
            "which is why the incident runbook exists and why campaign-level "
            "clustering beats per-post scoring during waves."
        ),
    }

    Path(args.out).write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    if args.markdown_out:
        lines = [
            "# Scale Simulation — Thresholds as Staffing Decisions",
            "",
            f"{args.daily_volume:,} posts/day (scored sample: {args.posts:,}) · true prevalence "
            f"{true_prevalence:.2%} · generated {report['generatedAt']}",
            "",
            "| Review threshold | Queue/day | Review-net recall | Reviewers | Daily cost | Cost per caught scam |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
        for row in sweep:
            lines.append(
                f"| {row['threshold']:.2f} | {row['queuePerDay']:,} | "
                f"{row['reviewNetRecall']:.1%} | {row['reviewersNeeded']} | "
                f"${row['dailyReviewCost']:,.0f} | ${row['costPerCaughtScam']:,.0f} |"
            )
        lines += ["", report["interpretation"], ""]
        Path(args.markdown_out).write_text("\n".join(lines), encoding="utf-8")
    if args.lab_summary:
        Path(args.lab_summary).write_text(
            "export const scaleSimulation = " + json.dumps(report, indent=2) + ";\n",
            encoding="utf-8",
        )

    print(
        json.dumps(
            {
                "posts": args.posts,
                "truePrevalence": report["corpus"]["truePrevalence"],
                "flaggedShare": report["operatingPoint"]["flaggedShare"],
                "reviewersAtOperatingPoint": report["operatingPoint"][
                    "reviewersNeededAtOperatingPoint"
                ],
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
